### PR TITLE
fix sles 12 - needs postgresql94 not postgresql93

### PR DESCRIPTION
**Pull request by monotek**
- fixing data/dependencies/sles.yml.
- added postgresql94
- removed postgresql93

### CODE REVIEW

**Comment by monotek** [comment]
Any way to see this merged anytime soon?

**Comment by monotek** [comment]
@crohr 
Any way to see this merged anytime soon?

**Comment by crohr** [comment]
@monotek sorry for the wait. Would the proposed fix be ok for you?

**Comment by crohr** [comment]
I'll actually go ahead and merge

**Comment by monotek** [comment]
Great thanks :-)

**Pull request merged**
