### PR TITLE
Add 'home' parameter in cli

### PR DESCRIPTION
**Pull request by thomasalrin**
#71

### CODE REVIEW

**Comment by bezreyhan** [comment]
+1

**Comment by benlangfeld** [comment]
With the exception of the advertising, 👍

**Comment by ctrabold** [comment]
I can confirm that the change works and custom `home` folders work as expected.

@thomasalrin you could remove "https://console.megam.io" from the `README.md` for merging. Or use a more generic URL e.g. https://pkgr.example.org. Nitpicking me would also remove the change on 'homepage' completely from this PR because it is not related to the 'home' parameter.

**Comment by thomasalrin** [comment]
@ctrabold done.

**Comment by ctrabold** [comment]
@benlangfeld ready to :ship:?

**Comment by benlangfeld** [comment]
@ctrabold @thomasalrin This PR was closed, and I'm not sure why, but it looks good to me.

**Comment by ctrabold** [comment]
@thomasalrin I wonder if you did close #72 by accident? Your patch looks good and should be merged. Rather close #71 as @benlangfeld suggested in his comment there.

**Comment by thomasalrin** [comment]
@ctrabold Ohh... that was an accident.

**Comment by ctrabold** [comment]
@benlangfeld re-opened. looks 💯  to me. Let's try 🚢  again? 😉

**Comment by benlangfeld** [comment]
I like this, but only @crohr can merge it.

**Comment by thomasalrin** [comment]
@crohr done rebase the commits.
Thank you:-)

**Pull request merged**
